```python
python manage.py runserver #启动服务器
python functional_tests.py #功能测试
python manage.py test functional_tests #第六章后的功能测试
python manage.py test #单元测试
python manage.py test lists #第六章后的单元测试

python manage.py makemigrations #数据库迁移命令
python manage.py migrate #创建数据库
```

## 第一章

1. Anaconda Prompt中运行`pip install Django`进行安装。

2. 编写functional_tests.py
 ```python
from selenium import webdriver
browser = webdriver.Chrome()
browser.get('http://localhost:8000')
assert 'Django' in browser.title
 ```

3. 跳转到该目录下或powershell输入`django-damin.py startproject suplerlists`
4. Anaconda Prompt运行`python manage.py runserver`
5. Spyder中运行functional_tests.py，显示成功
6. 目录下打开Linux Shell看一看。同步到github，下略。
 ```shell
ls
mv functional_tests.py superlists/
cd superlists
 ```

## 第二章

1. 关掉所有的，更新functional_tests.py代码（第23张ppt）

2. 到目录\21 _Software Testing Technology\suplerlists处Anaconda Prompt处启动`python manage.py runserver`

3. Anaconda Prompt到目录处运行测试`python functional_tests.py`
4. 新建functional_tests2.py并添加代码 (第30张ppt)

5. Anaconda Prompt运行`python functional_tests2.py`

## 第三章

1. Anaconda Prompt到目录处`python manage.py startapp lists`

2. 编辑list下的test.py如下，Anaconda Prompt到目录处运行`python manage.py test`
 ```python
from django.test import TestCase
class SmokeTest(TestCase):
    def test_bad_maths(self):
   	 self.assertEqual(1 + 1, 3)
 ```

3. 编辑list下的test.py如下，Anaconda Prompt到目录处运行`python manage.py test`
 ```python
from django.urls import resolve
from django.test import TestCase
from lists.views import home_page
class HomePageTest(TestCase):
    def test_root_url_resolves_to_home_page_view(self):
        found = resolve('/')
        self.assertEqual(found.func, home_page)
 ```

## 第三章续

4. 上接3步，编辑好test.py。到目录处Anaconda Prompt运行`python manage.py runserver`

5. 到目录处新开一个Anaconda Prompt，并运行（在目录处，下略）`python manage.py test`

6. 编辑views.py，添加如下后，在Anaconda Prompt重新运行`python manage.py test`
 ```python
from django.shortcuts import render
home_page = None
 ```

7. suplerlists\suplerlists中打开urls.py并改成如下后，在Anaconda Prompt运行`python manage.py test`
 ```python
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from lists import views
urlpatterns = [
    #path('admin/', admin.site.urls),
    url(r'^$',views.home_page,name='home'),
]
 ```

8. views.py改成如下，Anaconda Prompt运行`python manage.py test`并显示成功。
 ```python
from django.shortcuts import render
def home_page():
    pass
 ```

9. 修改test.py如下后并在Anaconda Prompt运行`python manage.py test`
 ```python
from django.urls import resolve
from django.test import TestCase
from django.http import HttpRequest
from lists.views import home_page
class HomePageTest(TestCase):
    def test_root_url_resolves_to_home_page_view(self):
        found = resolve('/')
        self.assertEqual(found.func, home_page)
    def test_home_page_returns_correct_html(self):
        request = HttpRequest()
        response = home_page(request)
        html = response.content.decode('utf8')
        self.assertTrue(html.startswith('<html>'))
        self.assertIn('<title>To-Do lists</title>', html)
        self.assertTrue(html.endswith('</html>'))
 ```

10. 多次修改view.py，最终改成如下后，在Anaconda Prompt中运行单元测试`python manage.py test`，并显示成功。在Anaconda Prompt运行功能测试，注意是tests2.py
 `python functional_tests2.py`。
 ```python
from django.shortcuts import render
from django.http import HttpResponse
def home_page(request):
     return HttpResponse('<html><title>To-Do lists</title></html>')
 ```

## 第四章

1.  TDD是一个长期的东西
2. Anaconda Prompt再运行一次功能测试`python functional_tests2.py`(如提示To-Do错误可能没开服务器)

3. 新建functional_tests3.py并添加代码 (第102张ppt，或4.pdf的41页)

4. Anaconda Prompt运行`python functional_tests3.py`，会提示`Unable to locate element: {"method":"tag name","selector":"h1"}`

## 第四章续

1. Anaconda Prompt并运行单元测试`python manage.py test`，并提示成功

2. list目录下创建templates文件夹，并创建home.html文件，并填写
 ```html
<html>
    <title>To-Do lists</title>
</html>
 ```

3. 修改views.py为如下，后运行`python manage.py test`，出现错误提示。
 ```python
from django.shortcuts import render
def home_page(request):
    return render(request, 'home.html')
 ```

4. 打开settings.py，在INSTALLED_APPS中添加  `'lists',`

5. 运行`python manage.py test`，会有如下错误。（文本编译器不同，一般不会出错）（是断言home.html末尾是不是</html>）
 ```shell
    self.assertTrue(html.endswith('</html>'))
AssertionError: False is not true
 ```

6.  查看test.py代码，修改以下函数如下，见4.pdf的47页。
 ```python
 from django.template.loader import render_to_string
 	def test_home_page_returns_correct_html(self):
           request = HttpRequest()
           response = home_page(request)
           html = response.content.decode('utf8')
           expected_html = render_to_string('home.html')
           self.assertEqual(html, expected_html)
 ```

7. 再把以上函数改成见4.pdf的47页下方的代码。②和③一样。删掉②后如下，同时修改函数名为test_uses_home_template。运行`python manage.py test`，提示成功。
 ```python
           response = self.client.get('/')
           self.assertTemplateUsed(response, 'home.html')
 ```

8. 可以改成`self.assertTemplateUsed(response, 'hom2e.html')` 后再运行`python manage.py test`，会出现错误提示 `Template 'hom2e.html' was not a template used to render the response. Actual template(s) used: home.html`。再改成正确的。此时也可以把test_root_url_resolves_to_home_page_view函数删掉了。

9. git中commit。修改home.html为如下，并`python functional_tests3.py`，提示 Unable to locate element: {"method":"id","selector":"id_new_item"}
 ```html
<html>
    <head>
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
    </body>
</html>
 ```

10. 多次修改home.html直至如下，并`python functional_tests3.py`，会提示any(row.text == '1: Buy peacock feathers' for row in rows)。

 ```html
<html>
    <head>
        <title>To-Do lists</title>
    </head>
     <body>
        <h1>Your To-Do list</h1>
         <input id="id_new_item" placeholder="Enter a to-do item" />
        <table id="id_list_table">
    </body>
</html>
 ```

11. functional_tests3.py中（见4.pdf的52页）添加`"New to-do item did not appear in table"`后，并`python functional_tests3.py`，会提示AssertionError: False is not true : New to-do item did not appear in table。

## 续第五章

1. 修改home.html文件，中间部分几行修改如下，并功能测`python functional_tests3.py`，浏览器会提示Forbidden 403，CSRF verification failed，命令行会提示no such element: Unable to locate element: {"method":"id","selector":"id_list_table"}。
 ```html
   <form method="POST">
  <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
   </form>
 ```

2. 如需要调试，可将functional_tests3.py中的time.sleep(1)改成10等时间。

3. 查看浏览器中详细的错误信息与建议，修改home.html如下，命令行会提示False is not true : New to-do item did not appear in table。
 ```html
           <form method="POST">
           <input name="item_tetxt" id="id_new_item" placeholder="Enter a to-do item" />
           {啊%csrf_toke%啊}
           </form>
 ```

4. 可以将sleep改回来。

5. 修改test.py，添加以下函数，并运行单元测`python manage.py test`。命令行会提示'A new list item' not found in '<html>\n......'，

 ```python
   def test_can_save_a_POST_request(self):
       response = self.client.post('/', data={'item_text': 'A new list item'})
       self.assertIn('A new list item', response.content.decode())
 ```

6. 修改views.py，假装让测试通过。并运行单元测`python manage.py test`。测试通过。
 ```python
   def home_page(request):
       if request.method == 'POST':
           return HttpResponse(request.POST['item_text'])
       return render(request, 'home.html')
 ```

7. 修改home.html中部分内容，如下。修改test.py中的test_can_save_a_POST_request函数为如下。并运行单元测`python manage.py test`，会提示AssertionError: No templates used to render the response。

 ```html
   <table id="id_list_table">
       <tr><td>{{ new_item_text }}</td></tr>
   </table>
 ```

 ```python
   def test_can_save_a_POST_request(self):
       response = self.client.post('/', data={'item_text': 'A new list item'})
       self.assertIn('A new list item', response.content.decode())
       self.assertTemplateUsed(response, 'home.html')
 ```

8. 修改views.py的函数如下，并运行单元测`python manage.py test`，会提示 request.POST['item_text']等。
 ```python
    return render(request, 'home.html', {
            'new_item_text': request.POST['item_text'],
    })
 ```

9. 修改views.py的函数如下，并运行功能测`python functional_tests3.py`，会提示False is not true : New to-do item did not appear in table等。
 ```python
    return render(request, 'home.html', {
            'new_item_text': request.POST.get('item_text', ''),
    })
 ```

10. 修改functional_tests3.py中函数的内容如下，运行`python functional_tests3.py`后提示False is not true : New to-do item did not appear in table. Contents were:Buy peacock feathers，were后如果为空说明home.html写错了。
 ```python
   self.assertTrue(
       any(row.text == '1: Buy peacock feathers' for row in rows),
       f"New to-do item did not appear in table. Contents were:\n{table.text}"
      )
 ```

11. 上面四行改为，运行`python functional_tests3.py`后会提示AssertionError: '1: Buy peacock feathers' not found in ['Buy peacock feathers']
 ```python
 self.assertIn('1: Buy peacock feathers', [row.text for row in rows]
 ```

12. 可修改home.html中代码为`<tr><td>1: {{ new_item_text }}</td></tr>`

13. 修改functional_tests3.py为functional_tests4.py中的代码，运行`python functional_tests4.py`后会提示AssertionError: '1: Buy peacock feathers' not found in ['Buy peacock feathers']

14. functional_tests4.py中的tearDown函数下添加如下函数。
 ```python
 def check_for_row_in_list_table(self, row_text):
    table = self.browser.find_element_by_id('id_list_table')
    rows = table.find_elements_by_tag_name('tr')
    self.assertIn(row_text, [row.text for row in rows])
 ```

15. 修改为functional_tests5.py中的代码，运行`python functional_tests5.py`后会提示AssertionError: '1: Buy peacock feathers' not found in ['Buy peacock feathers']

16. 修改tests.py函数如下，添加新的类，运行`python manage.py test`，会提示ImportError: cannot import name 'Item'
 ```python
from lists.models import Item
class ItemModelTest(TestCase):
     def test_saving_and_retrieving_items(self):
         略，见5.pdf的66页
 ```

17. 修改models.py如下，添加如下代码后再运行`python manage.py test`，会提示AttributeError: 'Item' object has no attribute 'save'。修改代码`Item`为`Item(models.Model)`，再运行`python manage.py test`，会有很多错误和django.db.utils.OperationalError: no such table: lists_item提示。
 ```python
class Item(object):
    pass
 ```

18. 数据库迁移命令`python manage.py makemigrations`，会提示- Create model Item。也可以看到新建了migrations文件夹，下有0001_initial.py、____init____.py和____pycache____文件夹。

19. 运行单元测试`python manage.py test lists`，提示AttributeError: 'Item' object has no attribute 'text'。

20. 修改models.py函数内容为`text = models.TextField()`，运行`python manage.py test lists`，会提示django.db.utils.OperationalError: no such column: lists_item.text。运行`python manage.py makemigrations`，并输入2退出。修改models.py函数内容为`text = models.TextField(default='')`，运行`python manage.py makemigrations`，会提示    - Add field text to item。最后运行`python manage.py test lists`，会提示OK通过。

## 第五章续

1. 在test.py中的test_can_save_a_POST_request(self)函数插入如下三行代码，从第二行起插入。运行`python manage.py test lists`，会提示AssertionError: 0 != 1错误。
 ```python
self.assertEqual(Item.objects.count(), 1)
new_item = Item.objects.first()
self.assertEqual(new_item.text, 'A new list item')
 ```

2. 在views.py中插入三行如下代码，在home_page(request)函数第一行起插入。运行`python manage.py test lists`，会提示OK。
 ```python
from lists.models import Item
item = Item()
item.text = request.POST.get('item_text', '')
item.save()
 ```

3. 修改views.py中return部分代码如下来重构。运行`python manage.py test lists`，会提示OK。
 ```python
     return render(request, 'home.html', {
            'new_item_text': item.text
    })
 ```

4. 在tests.py的HomePageTest类中添加如下代码。运行`python manage.py test lists`，会提示AssertionError: 1 != 0。
 ```python
def test_only_saves_items_when_necessary(self):
    self.client.get('/')
    self.assertEqual(Item.objects.count(), 0)
 ```

5. 修改views.py代码如下，运行`python manage.py test`，会提示OK。
 ```python
    if request.method == 'POST':
        new_item_text = request.POST['item_text']
        Item.objects.create(text=new_item_text)
    else:
        new_item_text = ''
    return render(request, 'home.html', {
            'new_item_text': new_item_text
    })
 ```

6. **Redirect after a POST。**修改tests.py代码test_can_save_a_POST_request函数部分。运行`python manage.py test`，会提示AssertionError: 200 != 302。
 ```python
self.assertEqual(response.status_code, 302)
self.assertEqual(response['location'], '/')
 ```

7. 修改views.py代码如下，运行`python manage.py test`，会提示OK。
 ```python
from django.shortcuts import redirect
def home_page(request):
    if request.method == 'POST':
        Item.objects.create(text=request.POST['item_text'])
        return redirect('/')
    return render(request, 'home.html')
 ```

8. **Better Unit Testing Practice: Each Test Should Test One Thing。**修改tests.py中的test_can_save_a_POST_request函数，并添加如下函数。运行`python manage.py test`，会提示OK。
 ```python
def test_redirects_after_POST(self):
    response = self.client.post('/', data={'item_text': 'A new list item'})
    self.assertEqual(response.status_code, 302)
    self.assertEqual(response['location'], '/')
 ```

9. **Rendering Items in the Template。**在tests.py中添加如下代码。运行`python manage.py test`，会提示AssertionError: 'itemey 1' not found in <html>\n等。
 ```python
def test_displays_all_list_items(self):
    Item.objects.create(text='itemey 1')
    Item.objects.create(text='itemey 2')
    #
    response = self.client.get('/')
    #
    self.assertIn('itemey 1', response.content.decode())
    self.assertIn('itemey 2', response.content.decode())
 ```

10. 在home.html中添加`{% for item in items %} <tr><td>1: {{ item.text }}</td></tr> {% endfor %}`语句，修改views.py中部分代码如下，运行`python manage.py test`，会提示OK。
 ```python
items = Item.objects.all()
return render(request, 'home.html', {'items': items})
 ```

11. 运行功能测试，`python functional_tests5.py`，会提示AssertionError: 'To-Do' not found in 'OperationalError at /'。浏览器访问http://localhost:8000/ ，可以看到错误的具体原因。

12. **Creating Our Production Database with migrate。**打开settings.py，可以看到DATABASES字段。输入`python manage.py migrate`创建数据库，可以看到文件夹内多了db.sqlite3文件。

13. 运行功能测试，`python functional_tests5.py`，会提示AssertionError: '2: Use peacock feathers to make a fly' not found in ['1: Buy peacock feathers', '1: Use peacock feathers to make a fly']。修改home.html中部分代码为`<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>`，运行功能测试，`python functional_tests5.py`，可以看到浏览器依次显示如下内容，命令行中显示AssertionError: Finish the test!。多次运行功能测试，`python functional_tests5.py`，浏览器中还会继续出现如下下方的内容。
 ```python
1: Buy peacock feathers
2: Use peacock feathers to make a fly
3: Buy peacock feathers
4: Use peacock feathers to make a fly
 ```

 ```python
5: Buy peacock feathers
6: Use peacock feathers to make a fly
 ```

14. 可以通过`rm db.sqlite3`和`python manage.py migrate --noinput`删掉，windows需关掉服务器后在Linux shell输入第一个命令，然后在anaconda promopt中输入第二个命令。重启服务器，可以看到浏览器中没有了上述的内容。

## 第六章

1. 新建文件夹和文件，mkdir functional_tests和touch functional_tests/____init____.py。接着输入git mv functional_tests5.py functional_tests/tests.py将functional_tests5.py移动到新建的文件夹里面并重命名。可以git status查看。

2. 以后使用`python manage.py test functional_tests`来功能测试。

## 第六章续

3. functional_tests下的tests.py中修改下面部分代码。删掉`if ____name____ == '__main__':`及后面代码。运行`python manage.py test functional_tests`后会提示AssertionError: Finish the test!
 ```python
from django.test import LiveServerTestCase
class NewVisitorTest(LiveServerTestCase):
    def test_can_start_a_list_and_retrieve_it_later(self):
        self.browser.get(self.live_server_url)
 ```

4. 运行单元测`python manage.py test`，功能测试和单元测就一起运行了，AssertionError: Finish the test!且Ran 7 tests in 7.282s（功能测1个，单元测6个）。可以运行`python manage.py test lists`，看到Ran 6 tests in 0.055s和OK。
5. 以后使用`python manage.py test lists`来单元测试。
6. **On Implicit and Explicit Waits, and Voodoo time.sleeps。**functional_tests下的tests.py中添加如下代码，同时删掉`check_for_row_in_list_table`函数，添加见6.pdf的90页 `wait_for_row_in_list_table`函数。删掉`test_can_start_a_list_and_retrieve_it_later`函数中的`time.sleep(1)`代码，同时把调用前者函数的部分改成调用`wait_for_row_in_list_table`函数。运行`python manage.py test`后会提示AssertionError: Finish the test!和Ran 7 tests in 5.250s，时间变短了。

 ```python
   from selenium.common.exceptions import WebDriverException
   MAX_WAIT = 10
 ```

7. 故意以几种方式打破错误。`wait_for_row_in_list_table`函数中的部分，改成`self.assertIn('foo', [row.text for row in rows])`，等待两次后，上面会出现一个AssertionError: 'foo' not found in ['1: Buy peacock feathers']。撤销修改。改成`table = self.browser.find_element_by_id('id_nothing')`，等待两次后，上面会出现一个Unable to locate element: {"method":"id","selector":"id_nothing"}。撤销修改。运行`python manage.py test`，提示AssertionError: Finish the test!。

## 第七章

1. **Ensuring We Have a Regression Test。**functional_tests下的tests.py中test_can_start_a_list_and_retrieve_it_later函数更名为test_can_start_a_list_for_one_user，并修改和删除部分如下，添加见7.pdf的99和100页的函数test_multiple_users_can_start_lists_at_different_urls。运行功能测试`python manage.py test functional_tests`后会提示Regex didn't match: '/lists/.+' not found in 'http://localhost:14533/'和Ran 2 tests in 10.339s和FAILED (failures=1)。
 ```python
   # The page updates again, and now shows both items on her list
   self.wait_for_row_in_list_table('2: Use peacock feathers to make a fly')
   self.wait_for_row_in_list_table('1: Buy peacock feathers')
   # Satisfied, she goes back to sleep
 ```

## 第七章续

2. **Iterating Towards the New Design**。修改lists文件夹内tests.py的test_redirects_after_POST(self)函数最后一行为`self.assertEqual(response['location'], '/lists/the-only-list-in-the-world/')`。运行单元测python manage.py test lists，会提示AssertionError: '/' != '/lists/the-only-list-in-the-world/'。

3. 修改lists文件夹内views.py，其中一行为return redirect('/lists/the-only-list-in-the-world/')，运行功能测试python manage.py test functional_tests，FAILED (errors=2)都失败了。在lists文件夹tests.py添加新的测试类，将test_displays_all_list_items函数内容复制到类下并修改为如下。运行单元测试`python manage.py test lists`，提示网址不存在Response code was 404 (expected 200)和......F，前面六个用例通过第七个F失败。
   ```python
   class ListViewTest(TestCase):
   def test_displays_all_items(self):
       Item.objects.create(text='itemey 1')
       Item.objects.create(text='itemey 2')
       response = self.client.get('/lists/the-only-list-in-the-world/')
       self.assertContains(response, 'itemey 1')
       self.assertContains(response, 'itemey 2')
   ```

4. 修改urls.py一部分如下，运行单元测试`python manage.py test lists`，会提示 module 'lists.views' has no attribute 'view_list'。
   ```python
       url(r'^$', views.home_page, name='home'),
       url(r'^lists/the-only-list-in-the-world/$', views.view_list, name='view_list'),
   ```

5. lists文件夹views.py修改一部分如下，运行单元测试`python manage.py test lists`会提示ValueError: The view lists.views.view_list didn''t return an HttpResponse object. It returned None instead.和FAILED (errors=1)。继续修改一部分如下方下面，运行单元测试`python manage.py test lists`会提示OK。运行功能测试`python manage.py test functional_tests`，后会提示AssertionError: '2: Use peacock feathers to make a fly' not found in ['1: Buy peacock feathers']等错误。
   ```python
   def view_list(request):
   pass
   ```
   ```python
   def view_list(request):
   items = Item.objects.all()
   return render(request, 'home.html', {'items': items})
   ```

   >单元测试是逻辑测试，不测试内容。单元测都过了逻辑没问题，view、url没问题。但没覆盖到内容，在template里面。
   >

6. 修改lists文件夹templates/home.html中一行代码为`<form method="POST" action="/">`，运行功能测试python manage.py test functional_tests，之前的第一个过了，测两个人的没过。FAILED (errors=1)和AssertionError: 'Buy peacock feathers' unexpectedly found in 'Your To-Do list\n1: Buy peacock feathers'。

   > Message: 'geckodriver' executable needs to be in PATH.是因为functional_tests\tests.py中的代码写成了webdriver.Firefox()。

7. **Green? Refactor**。在Linux shell中输入grep -E "class|def" lists/tests.py，可以看到下面部分。删掉lists/tests.py中HomePageTest类中的test_displays_all_list_items函数。此时运行单元测试`manage.py test lists`会显示Ran 6 tests in 0.031s而不是之前的七个。
   ```python
   class HomePageTest(TestCase):
    def test_uses_home_template(self):
    def test_can_save_a_POST_request(self):
    def test_redirects_after_POST(self):
    def test_only_saves_items_when_necessary(self):
    def test_displays_all_list_items(self):
   class ItemModelTest(TestCase):
    def test_saving_and_retrieving_items(self):
   class ListViewTest(TestCase):
    def test_displays_all_items(self):
   ```

8. **Another Small Step: A Separate Template for Viewing Lists**。lists/tests.py的ListViewTest类下添加如下函数。运行单元测试`manage.py test lists`会提示False is not true : Template 'list.html' was not a template used to render the response. Actual template(s) used: home.html。

   ```python
   def test_uses_list_template(self):
    response = self.client.get('/lists/the-only-list-in-the-world/')
    self.assertTemplateUsed(response, 'list.html')
   ```

9. 修改Views.py内view_list函数的一行代码为`return render(request, 'list.html', {'items': items})`，运行单元测试`manage.py test lists`会提示django.template.exceptions.TemplateDoesNotExist: ltst.html。在suplerlists\lists\templates目录下新建list.html文件。运行单元测试manage.py test lists会提示False is not true : Couldn''t find 'itemey 1' in response。将home.html内容拷贝到list.html中，运行单元测试manage.py test lists会提示Ran 7 tests in 0.047s和OK。

10. 修改home.html代码如下，注意保留其余部分。运行单元测试manage.py test lists会提示Ran 7 tests in 0.052s和OK。
   ```html
<body>
    <h1>Start a new To-Do list</h1>
    <form method="POST">
       <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
       {% csrf_token %}
    </form>
</body>
   ```

11. 修改lists/views.py的home_page代码如下，最后两行有改动。运行功能测试python manage.py test functional_tests，提示AssertionError: '1: Buy milk' not found in ['1: Buy peacock feathers', '2: Buy milk']
   ```python
if request.method == 'POST':
    Item.objects.create(text=request.POST['item_text'])
    return redirect('/lists/the-only-list-in-the-world/')
return render(request, 'home.html')
   ```

12. **A Test Class for New List Creation**。把lists/tests.py下的test_can_save_a_POST_request和test_redirects_after_POST函数移动到该文件内新建的NewListTest类下并把client.post('/',修改为self.client.post('/lists/new',并修改第二个函数如下。运行单元测试manage.py test lists会提示 AssertionError: 404 != 302 : Response didn't redirect as expected: Response code was 404 (expected 302)。
   ```python
def test_redirects_after_POST(self):
    response = self.client.post('/lists/new', data={'item_text': 'A new list item'})
    self.assertRedirects(response, '/lists/the-only-list-in-the-world/') 
   ```

13. A URL and View for New List Creation。修改urls.py中的部分内容为如下。运行单元测试`manage.py test lists`会提示 AttributeError: module 'lists.views' has no attribute 'new_list'
   ```python
   url(r'^$', views.home_page, name='home'),
   url(r'^lists/new$', views.new_list, name='new_list'),
   url(r'^lists/the-only-list-in-the-world/$', views.view_list, name='view_list'),
   ```

15. views.py中添加函数和代码如下，运行单元测试`manage.py test lists`后会提示
ValueError: The view lists.views.new_list didn''t return an HttpResponse object. It returned None instead。第二行代码改为`return redirect('/lists/the-only-list-in-the-world/')`，运行单元测试`manage.py test lists`会提示AssertionError: 0 != 1。第二行代码改为下方代码，运行单元测试`manage.py test lists`会提示Ran 7 tests in 0.060s和OK。运行功能测试`python manage.py test functional_tests`后会提示AssertionError: '1: Buy milk' not found in ['1: Buy peacock feathers', '2: Buy milk']和Ran 2 tests in 24.343s和FAILED (failures=2)。
   ```python
def new_list(request):
	pass
   ```
   ```python
	Item.objects.create(text=request.POST['item_text'])
	return redirect('/lists/the-only-list-in-the-world/')
   ```
16. **Removing Now-Redundant Code and Tests**。简化views.py中的home_page部分，只剩下`return render(request, 'home.html')`。删除lists/tests.py下冗余的`test_only_saves_items_when_necessary`函数。运行单元测Ran 6 tests in 0.047s
    OK，运行功能测试提示错误selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"id_list_table"}等。
17. **A Regression! Pointing Our Forms at the New URL**。修改home.html和lists.heml中的代码为`<form method="POST" action="/lists/new">`，运行功能测试，提示AssertionError: '1: Buy milk' not found in ['1: Buy peacock feathers', '2: Buy milk']和Ran 2 tests in 24.921s和FAILED (failures=2)等。

> 留下你的评论
> Your text here

